### PR TITLE
fix: handle file read instead of silently exiting

### LINKED ISSUE #14: Missing ~/.nvmd/setting.json file causes `nvmd list` command to silently exit
Steps to reproduces:

- Install nvm-desktop (v4.0.5)
- install any node version
- run `nvmd list`

Observation:

- No output (stdin or stderr) is given
- User is not notified if the node version was installed or that the `setting.json` file is required

Expected:

- Looks like the setting.json file is not mandatory.
- Continue to process the command without it, instead of exiting

### PR DESCRIPTION
**Pull request by svihpinc**
Fixes #14

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -40,7 +40,8 @@ fn get_bin_path(version: &str) -> Option<OsString> {
 fn get_installation_path() -> Result<Option<PathBuf>> {
     if let Some(mut setting_path) = NVMD_PATH.clone() {
         setting_path.push("setting.json");
-        let setting_content = read_to_string(&setting_path)?;
+
+        let setting_content = read_to_string(&setting_path).or::<Error>(Ok("".to_string()))?;
```
Comment (1111mp) [inline src/common.rs:44]: `let project_version = read_to_string(&nvmdrc).unwrap_or("".to_string());`
It would be better to use `unwrap_or` directly.

Comment (svihpinc) [reply src/common.rs]: updated

**Review by 1111mp — APPROVED** [review]

**Comment by 1111mp** [comment]
Thank you for your work 🌹
